// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojbybuvypbvvkymptqqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qYnlidXZ5cGJ2dmt5bXB0cXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MjAwODEsImV4cCI6MjA2NTA5NjA4MX0.1Li-QIWTxNRvZM3Iv4hrodqDQRaaa7L43v-CWSbDZzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);